export const PICTURE_FETCHING = "PICTURE_FETCHING"
export const PICTURE_FETCHED = "PICTURE_FETCHED";

export const GIF_FETCHED = "GIF_FETCHED"
export const GIF_FETCHING = "GIF_FETCHING";

export const GAME_FETCHING = "GAME_FETCHING"
export const GAME_FETCHED = "GAME_FETCHED";

export const VIDEO_FETCHING = "VIDEO_FETCHING"
export const VIDEO_FETCHED = "VIDEO_FETCHED";